### PR TITLE
1.16.5 Dependency updates + intellij stuff removed

### PR DESCRIPTION
**Pull request by davidalb97**
I took the liberty of updating the dependencies of your mod and did the following changes:
- Now ignoring .idea/ folder on .gitignore;
- Removed .idea/ from remote repository;
- Updated dependencies to mc 1.16.5;
- Updated Gradle to 6.9.1 (last Gradle version that does not require Java 16);
- Added more expanded variables on fabric.mod.json.

PS: If you could create a [1.17 branch](https://github.com/davidalb97/fabric-console-fork/tree/1.17.1), I could also create a PR with the 1.17.1 changes.

### CODE REVIEW

**Comment by LoganDark** [comment]
> * Now ignoring .idea/ folder on .gitignore;
> * Removed .idea/ from remote repository;

No thanks. The IDEA project files store the code formatter settings, and also generally make it easy to open & run the project.

Other than that, I appreciate your fixes, especially updating toolchain stuff. I'm not in a position to merge right now because I got a new computer and it runs Windows, which makes any sort of development work almost impossible. I'll try to get things set up on this cursed operating system and I'll let you know if it turns out ok.

In the meantime, could you also open a PR to [`fabric-barebones`](https://github.com/LoganDark/fabric-barebones), my template repository?

**Comment by LoganDark** [comment]
I had to make some changes to the 1.16 branch to get it to build. Sorry if the merge conflicts are a nightmare - feel free to paste all the build.gradle / gradle.properties / fabric.mod.json changes into a separate PR...

**Comment by LoganDark** [comment]
I've integrated most of your PR into the 1.15 and 1.16 branches, and updated the mod to 1.17 in the 1.17 branch. Thank you for the wake-up call!

**Comment by davidalb97** [comment]
> No thanks. The IDEA project files store the code formatter settings, and also generally make it easy to open & run the project.

I'm sorry that I deleted them, I thought that you imported the project as a gradle project on intellij and forgot to add it to the .gitignore.

> In the meantime, could you also open a PR to [`fabric-barebones`](https://github.com/LoganDark/fabric-barebones), my template repository?

I could do that, should I update it to 1.16.5 or 1.17.1?

**Pull request closed without merging**
